<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\RRC.Abstractions\RRC.Abstractions.csproj" />
    <ProjectReference Include="..\RRC.Simulation\RRC.Simulation.csproj" />
  </ItemGroup>
</Project>
